merge changes from  Joachims

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47,10 +47,21 @@ if [ "$1" = "kde4" ]; then
    if [ config = "debug" ]; then
      cmake "$currentDir" -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` -DCMAKE_BUILD_TYPE=debugfull
    else
-     cmake "$currentDir" -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix`  # create Makefile
+     cmake "$currentDir" -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` 
+   fi
+   if [ $? -ne 0 ]
+   then
+      echo "CMake errors."
+      exit
    fi
    echo Running make.
    make                                           # run make (compile and link)
+   if [ $? -ne 0 ]
+   then
+      echo "Compile errors."
+      exit
+   fi
+
    echo If everything went OK then KDiff3 was built in the subdir "$outputDir".
    echo "Install as root (requires password)."
    sudo make install                              # install as root user
